name: Valist Tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
          npm run test
