name: Lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install modules.
        run: yarn
      - name: Lint code.
        run: cd ./packages/valist-sdk && yarn lint
      - name: Prettier code.
        run: cd ./packages/valist-sdk && yarn prettier
