name: Build & Sign Sapphire Android

on:
  push:
    branches:
      - feature/android

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm

      - name: Build Web App Bundle
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: webui
          path: ./packages/valist-web/out/

      - name: Unit Tests
        run: npm run test

  build-android:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm

      - uses: actions/download-artifact@v2
        with:
          name: webui
          path: ./packages/valist-web/out/

      - name: Install Capacitor Deps
        run: |
          npm install

      - name: Sync Capacitor Build
        run: npx cap sync

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Generate Release APK
        run: (cd android && ./gradlew bundleReleas)

      - name: Test Path
        run: ls ./android/app/build/outputs

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ./android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # - name: Valist Publish
      #   uses: valist-io/valist-github-action@v2.5.6
      #   with:
      #     private-key: ${{ secrets.VALIST_SIGNER }}
      #     account: valist
      #     project: sapphire
      #     release: ${{ github.ref_name }}
      #     path: /out
      #     install-name: sapphire
      #     install-android-arm64:

      # - name: Upload Android Release to Play Store
      #   uses: r0adkll/upload-google-play@v1.0.18
      #   with:
      #     serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
      #     packageName: io.valist.app
      #     releaseFile: ${{steps.sign_app.outputs.signedReleaseFile}}
