name: Build & Sign Sapphire Android

on:
  push:
    branches:
      - feature/android

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm

      - name: Build Web App Bundle
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: webui
          path: ./packages/valist-web/out/

      # - name: Unit Tests
      #   run: npm run test

  # build-android:
  #   runs-on: ubuntu-latest
  #   needs: build-web
  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16"
  #         cache: npm

  #     - name: Download Webui
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: webui
  #         path: ./packages/valist-web/out/

  #     - name: Install Capacitor Deps
  #       run: |
  #         npm install

  #     - name: Sync Capacitor Build
  #       run: npx cap sync android

  #     - name: Setup Java
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: "adopt"
  #         java-version: "11"

  #     - name: Generate Release APK
  #       run: (cd android && ./gradlew bundleReleas)

  #     - name: Sign APK
  #       uses: r0adkll/sign-android-release@v1
  #       id: sign_app
  #       with:
  #         releaseDirectory: ./android/app/build/outputs/bundle/release
  #         signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
  #         alias: ${{ secrets.ANDROID_ALIAS }}
  #         keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
  #         keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

  #     - name: Upload Signed APK
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: android-apk
  #         path: ./android/app/build/outputs/bundle/release/app-release.aab

  # - name: Upload Android Release to Play Store
  #   uses: r0adkll/upload-google-play@v1.0.18
  #   with:
  #     serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
  #     packageName: io.valist.app
  #     releaseFile: ${{steps.sign_app.outputs.signedReleaseFile}}

  build-electron:
    runs-on: ${{ matrix.os }}
    needs: build-web
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Download Webui
        uses: actions/download-artifact@v2
        with:
          name: webui
          path: ./packages/valist-web/out/

      - name: Install Electron dependencies
        run: (cd electron && npm install)

      - name: Sync Electron Build
        run: |
          mkdir ./electron/app
          mv ./packages/valist-web/out/* ./electron/app

      - name: Build & sign
        run: |
          make electron-sign
        env:
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          CSC_LINK: ${{ secrets.APPLE_DEV_ID_CERT }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_DEV_ID_CERT_PASS }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Upload the Archive
        uses: actions/upload-artifact@v3
        with:
          name: sapphire-${{ matrix.os }}
          path: ./electron/dist
          if-no-files-found: error

  # valist-publish:
  #   runs-on: ubuntu-latest
  #   needs: [build-android, build-electron]
  #   steps:
  #     - name: Fetch Sapphire Android
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: sapphire-android
  #         path: /artifacts

  #     - name: Fetch Sapphire Darwin
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: sapphire-macos-latest
  #         path: /artifacts

  #     - name: Fetch Sapphire Windows
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: sapphire-windows-latest
  #         path: /artifacts

  #     - name: Fetch Sapphire Linux
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: sapphire-linux-latest
  #         path: /artifacts

  # - name: Valist Publish
  #   uses: valist-io/valist-github-action@v2.5.6
  #   with:
  #     private-key: ${{ secrets.VALIST_SIGNER }}
  #     account: valist
  #     project: sapphire
  #     release: ${{ github.ref_name }}
  #     path: /artifacts
  #     install-name: sapphire
  #     install-android-arm64: release-unsigned-signed.apk
  #     install-darwin-amd64: valist-1.0.0-mac.zip
  #     install-windows-amd64: sapphire.exe
